### ISSUE TITLE
Compatibility with chai-as-promised

### ISSUE THREAD

**Issue by stevenvachon** [zation/chai-like#5]
``` js
var result = Promise.resolve().then(function(){ return [ {key:"value"} ] });

return expect(result).to.eventually.be.like([ {key:"value"} ]);
```

results in

``` js
AssertionError: expected { Object (_id, _state, ...) } to like [ { key: 'value' } ]
 at null.<anonymous> (node_modules/chai-like/lib/chai-like.js:37:10)
 at ctx.(anonymous function) [as like] (node_modules/chai/lib/chai/utils/addMethod.js:40:25)
 at Context.<anonymous> (test.js:85:35)
```

**Comment by stevenvachon** [comment]
Hello?

Is the problem perhaps in `chai-as-promised`? I'm not versed on writing chai plugins.

**Comment by stevenvachon** [comment]
Is the problem perhaps in `chai-as-promised`? I'm not versed on writing chai plugins.

**Comment by benvan** [comment]
I've just had the same problem.

To fix this, you need to make sure chai-like is loaded before chai-as-promised, e.g.

```
chai.use(chaiLike);
chai.use(chaiAsPromised);
```
